# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: complex.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'complex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomplex.proto\x12\x0f\x65xample.complex\"!\n\x05\x44ummy\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xe4\x01\n\x07\x43omplex\x12)\n\tdummy_one\x18\x01 \x01(\x0b\x32\x16.example.complex.Dummy\x12*\n\ndummy_list\x18\x02 \x03(\x0b\x32\x16.example.complex.Dummy\x12\x39\n\tdummy_map\x18\x03 \x03(\x0b\x32&.example.complex.Complex.DummyMapEntry\x1aG\n\rDummyMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.example.complex.Dummy:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLEX_DUMMYMAPENTRY']._loaded_options = None
  _globals['_COMPLEX_DUMMYMAPENTRY']._serialized_options = b'8\001'
  _globals['_DUMMY']._serialized_start=34
  _globals['_DUMMY']._serialized_end=67
  _globals['_COMPLEX']._serialized_start=70
  _globals['_COMPLEX']._serialized_end=298
  _globals['_COMPLEX_DUMMYMAPENTRY']._serialized_start=227
  _globals['_COMPLEX_DUMMYMAPENTRY']._serialized_end=298
# @@protoc_insertion_point(module_scope)
