// source: complex.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.example.complex.Complex', null, global);
goog.exportSymbol('proto.example.complex.Dummy', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.example.complex.Dummy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.example.complex.Dummy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.example.complex.Dummy.displayName = 'proto.example.complex.Dummy';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.example.complex.Complex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.example.complex.Complex.repeatedFields_, null);
};
goog.inherits(proto.example.complex.Complex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.example.complex.Complex.displayName = 'proto.example.complex.Complex';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.example.complex.Dummy.prototype.toObject = function(opt_includeInstance) {
  return proto.example.complex.Dummy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.example.complex.Dummy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.Dummy.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.example.complex.Dummy}
 */
proto.example.complex.Dummy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.example.complex.Dummy;
  return proto.example.complex.Dummy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.example.complex.Dummy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.example.complex.Dummy}
 */
proto.example.complex.Dummy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.example.complex.Dummy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.example.complex.Dummy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.example.complex.Dummy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.Dummy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.example.complex.Dummy.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.example.complex.Dummy} returns this
 */
proto.example.complex.Dummy.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.example.complex.Dummy.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.example.complex.Dummy} returns this
 */
proto.example.complex.Dummy.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.example.complex.Complex.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.example.complex.Complex.prototype.toObject = function(opt_includeInstance) {
  return proto.example.complex.Complex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.example.complex.Complex} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.Complex.toObject = function(includeInstance, msg) {
  var f, obj = {
    dummyOne: (f = msg.getDummyOne()) && proto.example.complex.Dummy.toObject(includeInstance, f),
    dummyListList: jspb.Message.toObjectList(msg.getDummyListList(),
    proto.example.complex.Dummy.toObject, includeInstance),
    dummyMapMap: (f = msg.getDummyMapMap()) ? f.toObject(includeInstance, proto.example.complex.Dummy.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.example.complex.Complex}
 */
proto.example.complex.Complex.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.example.complex.Complex;
  return proto.example.complex.Complex.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.example.complex.Complex} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.example.complex.Complex}
 */
proto.example.complex.Complex.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.example.complex.Dummy;
      reader.readMessage(value,proto.example.complex.Dummy.deserializeBinaryFromReader);
      msg.setDummyOne(value);
      break;
    case 2:
      var value = new proto.example.complex.Dummy;
      reader.readMessage(value,proto.example.complex.Dummy.deserializeBinaryFromReader);
      msg.addDummyList(value);
      break;
    case 3:
      var value = msg.getDummyMapMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.example.complex.Dummy.deserializeBinaryFromReader, "", new proto.example.complex.Dummy());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.example.complex.Complex.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.example.complex.Complex.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.example.complex.Complex} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.complex.Complex.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDummyOne();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.example.complex.Dummy.serializeBinaryToWriter
    );
  }
  f = message.getDummyListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.example.complex.Dummy.serializeBinaryToWriter
    );
  }
  f = message.getDummyMapMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.example.complex.Dummy.serializeBinaryToWriter);
  }
};


/**
 * optional Dummy dummy_one = 1;
 * @return {?proto.example.complex.Dummy}
 */
proto.example.complex.Complex.prototype.getDummyOne = function() {
  return /** @type{?proto.example.complex.Dummy} */ (
    jspb.Message.getWrapperField(this, proto.example.complex.Dummy, 1));
};


/**
 * @param {?proto.example.complex.Dummy|undefined} value
 * @return {!proto.example.complex.Complex} returns this
*/
proto.example.complex.Complex.prototype.setDummyOne = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.example.complex.Complex} returns this
 */
proto.example.complex.Complex.prototype.clearDummyOne = function() {
  return this.setDummyOne(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.example.complex.Complex.prototype.hasDummyOne = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Dummy dummy_list = 2;
 * @return {!Array<!proto.example.complex.Dummy>}
 */
proto.example.complex.Complex.prototype.getDummyListList = function() {
  return /** @type{!Array<!proto.example.complex.Dummy>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.example.complex.Dummy, 2));
};


/**
 * @param {!Array<!proto.example.complex.Dummy>} value
 * @return {!proto.example.complex.Complex} returns this
*/
proto.example.complex.Complex.prototype.setDummyListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.example.complex.Dummy=} opt_value
 * @param {number=} opt_index
 * @return {!proto.example.complex.Dummy}
 */
proto.example.complex.Complex.prototype.addDummyList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.example.complex.Dummy, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.example.complex.Complex} returns this
 */
proto.example.complex.Complex.prototype.clearDummyListList = function() {
  return this.setDummyListList([]);
};


/**
 * map<string, Dummy> dummy_map = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.example.complex.Dummy>}
 */
proto.example.complex.Complex.prototype.getDummyMapMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.example.complex.Dummy>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.example.complex.Dummy));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.example.complex.Complex} returns this
 */
proto.example.complex.Complex.prototype.clearDummyMapMap = function() {
  this.getDummyMapMap().clear();
  return this;};


goog.object.extend(exports, proto.example.complex);
