// source: oneofs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.example.oneofs.Result', null, global);
goog.exportSymbol('proto.example.oneofs.Result.ResultCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.example.oneofs.Result = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.example.oneofs.Result.oneofGroups_);
};
goog.inherits(proto.example.oneofs.Result, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.example.oneofs.Result.displayName = 'proto.example.oneofs.Result';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.example.oneofs.Result.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.example.oneofs.Result.ResultCase = {
  RESULT_NOT_SET: 0,
  MESSAGE: 1,
  CODE: 2
};

/**
 * @return {proto.example.oneofs.Result.ResultCase}
 */
proto.example.oneofs.Result.prototype.getResultCase = function() {
  return /** @type {proto.example.oneofs.Result.ResultCase} */(jspb.Message.computeOneofCase(this, proto.example.oneofs.Result.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.example.oneofs.Result.prototype.toObject = function(opt_includeInstance) {
  return proto.example.oneofs.Result.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.example.oneofs.Result} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.oneofs.Result.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    code: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.example.oneofs.Result}
 */
proto.example.oneofs.Result.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.example.oneofs.Result;
  return proto.example.oneofs.Result.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.example.oneofs.Result} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.example.oneofs.Result}
 */
proto.example.oneofs.Result.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.example.oneofs.Result.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.example.oneofs.Result.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.example.oneofs.Result} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.example.oneofs.Result.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.example.oneofs.Result.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.example.oneofs.Result} returns this
 */
proto.example.oneofs.Result.prototype.setMessage = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.example.oneofs.Result.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.example.oneofs.Result} returns this
 */
proto.example.oneofs.Result.prototype.clearMessage = function() {
  return jspb.Message.setOneofField(this, 1, proto.example.oneofs.Result.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.example.oneofs.Result.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 code = 2;
 * @return {number}
 */
proto.example.oneofs.Result.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.example.oneofs.Result} returns this
 */
proto.example.oneofs.Result.prototype.setCode = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.example.oneofs.Result.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.example.oneofs.Result} returns this
 */
proto.example.oneofs.Result.prototype.clearCode = function() {
  return jspb.Message.setOneofField(this, 2, proto.example.oneofs.Result.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.example.oneofs.Result.prototype.hasCode = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.example.oneofs);
